-- 코드를 입력하세요
SELECT U.USER_ID , U.NICKNAME , CONCAT(U.CITY ,CONCAT(" ", CONCAT(U.STREET_ADDRESS1 , CONCAT(" " , U.STREET_ADDRESS2)))) AS 전체주소 , CONCAT(SUBSTRING(U.TLNO,1,3),CONCAT('-',CONCAT(SUBSTRING(U.TLNO,4,4),CONCAT('-',SUBSTRING(U.TLNO,8,4))))) AS 전화번호
FROM USED_GOODS_USER AS U
WHERE U.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >=3
)
ORDER BY USER_ID DESC;