-- 코드를 작성해주세요
SELECT SUM(H.SCORE) AS SCORE , H.EMP_NO AS EMP_NO , E.EMP_NAME AS EMP_NAME , E.POSITION AS POSITION , E.EMAIL AS EMAIL
FROM HR_GRADE H
JOIN HR_EMPLOYEES E
ON H.EMP_NO = E.EMP_NO
WHERE H.YEAR = '2022'
GROUP BY H.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
